### ISSUE TITLE
No way to specify `--experimental` for `render` function

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build-conda-compat#56]
While [trying](https://github.com/conda-forge/zlib-feedstock/pull/83) to switch zlib to rattler, I need a [feature](https://prefix-dev.github.io/rattler-build/latest/multiple_output_cache/) that's currently under an experimental flag. Aside from the problem of not being able to [specify](https://github.com/conda-forge/conda-smithy/issues/2057) this through smithy yet, the larger issue is that this is not configurable in the compat layer here.

I've monkey-patched my local install to do:
```diff
                    run_args = [
                        "rattler-build",
                        "build",
                        "--render-only",
                        "--recipe",
                        self.path,
                        "--target-platform",
                        platform_and_arch,
                        "--build-platform",
                        platform_and_arch,
+                      "--experimental",
                    ]
```
which still runs into a rendering error:
```
  File "E:\miniforge\envs\smithy-dev\Lib\site-packages\rattler_build_conda_compat\render.py", line 317, in render
    m.config.variant = package_variants[0]
                       ~~~~~~~~~~~~~~~~^^^
```
which I solved as follows:
```diff
                        ):
                            package_variants.remove(pkg_variant)

-           m.config.variant = package_variants[0]
+           m.config.variant = package_variants[0] if package_variants else []

            # These are always the full set.  just 'variants' is the one that gets
            #     used mostly, and can be reduced
```
That way I was able to get a basic rerender to succeed at least (though still running into issues on the build invocation, which'll have to be fixed in smithy).

**Comment by h-vetinari** [comment]
@wolfv @baszalmstra @nichmor 
Any help with how an API for using `--experimental` should look like, so that smithy can build on top (https://github.com/conda-forge/conda-smithy/issues/2057).

**Comment by nichmor** [comment]
hey @h-vetinari ! let me take a look at this today! sorry for long reply time

**Comment by nichmor** [comment]
hey @h-vetinari - sorry I'm on vacation now - maybe @wolfv or @tdejager will could take a look

**Comment by h-vetinari** [comment]
Ping @nichmor @wolfv

**Comment by h-vetinari** [comment]
FWIW, I reapplied the monkeypatch to add `--experimental` to `run_args` again on the newest 1.2.2, and I'm still running into https://github.com/prefix-dev/rattler-build-conda-compat/issues/58 despite https://github.com/prefix-dev/rattler-build-conda-compat/pull/59, and thus the second patch also remains necessary.

**Comment by h-vetinari** [comment]
![Image](https://github.com/user-attachments/assets/c06a6d8a-e0f4-41c7-a9e8-5ab4b3122c21)

**Comment by h-vetinari** [comment]
https://github.com/conda-forge/conda-smithy/issues/2057 is collecting more and more examples where `cache:` (and thus `--experimental`) is needed.

**Comment by wolfv** [comment]
Yes, I think part of the reason why it's "experimental" right now is because we wanted to make sure that the semantics are correct. I think we should fix the issue you discovered on Windows and write up how it works, present that to the conda/conda-forge community and lift it out of experimental late december, early january. How does that sound?

**Comment by chrisburr** [comment]
I also ran into this for [root-feedstock](https://github.com/conda-forge/root-feedstock/), I shuffled the build a bit to avoid the cache key for now but I still have the issue with:

```
  File "/opt/conda/lib/python3.12/site-packages/conda_forge_ci_setup/utils.py", line 76, in get_built_distribution_names_and_subdirs
    metas = rattler_build_conda_compat.render.render(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/rattler_build_conda_compat/render.py", line 316, in render
    m.config.variant = package_variants[0]
                       ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

during `validate_recipe_outputs`, see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1165620&view=logs&jobId=aa85f627-05cc-5265-2465-79d7168d3859&j=aa85f627-05cc-5265-2465-79d7168d3859&t=17d89be7-40ff-5523-eff5-62cb36c6dac8).

Is there a workaround? Or shall I open a PR with `m.config.variant = package_variants[0] if package_variants else []`?

**Comment by chrisburr** [comment]
I see a PR has appeared which looks like it might contain the proper fix for this: https://github.com/prefix-dev/rattler-build-conda-compat/pull/68

@wolfv @nichmor is there any chance of you taking a look at this and making a release? I'm happy to help if I can as I'll otherwise need to port a recipe back to the old recipe format.

**Comment by chrisburr** [comment]
Dumping here, it seems like the correct patch is (i.e. default to a dict instead of a list):

```diff
---src/rattler_build_conda_compat/render.py
+++src/rattler_build_conda_compat/render.py
                        ):
                            package_variants.remove(pkg_variant)

-           m.config.variant = package_variants[0]
+           m.config.variant = package_variants[0] if package_variants else {}

            # These are always the full set.  just 'variants' is the one that gets
            #     used mostly, and can be reduced
```

Applying https://github.com/prefix-dev/rattler-build-conda-compat/pull/68 doesn't help.

**Comment by minrk** [comment]
`package_variants` being empty means there is a bug in the filtering of 'used variants.' Setting it to an empty dict does allow the code to proceed in this case, but it means ignoring a real error, and it's unclear what other failure might happen.

Since `root` is a multi-output recipe with inter-output dependencies and [has a variant pin](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/e1c0e1023fef2692dd79445ac9b4140642038297/recipe/conda_build_config.yaml#L891), there's a good chance you are hitting https://github.com/prefix-dev/rattler-build-conda-compat/pull/71

**Comment by minrk** [comment]
As a note, it _is_ possible to set

```
RATTLER_BUILD_EXPERIMENTAL=true
```

in the env, which enables experimental features.

So you can do:

```
RATTLER_BUILD_EXPERIMENTAL=true conda-smithy rerender
```

to rerender a recipe with `cache` today. I'm not sure where to read that option from in conda-smithy (conda-forge.yml?), but it doesn't need any changes to this package in order to do so.

**Comment by vepadulano** [comment]
Hi, I have a followup to this issue. I am trying to rerender the same feedstock https://github.com/conda-forge/root-feedstock/, just from the main branch, no changes applied. Indeed #71 seems to bring some progress, I don't see the `IndexError: list index out of range` anymore. Now I see a different issue, though the stacktrace seems to be in `conda-smithy`

```
root-feedstock/ : PYTHONPATH=$PWD/rattler-build-conda-compat/install/lib/python3.13/site-packages:$PYTHONPATH conda-smithy rerender
[...]
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/cli.py", line 608, in __call__
    self._call(args, tmpdir)
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/cli.py", line 613, in _call
    configure_feedstock.main(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        args.feedstock_directory,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        temporary_directory=temporary_directory,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 2909, in main
    render_azure(env, config, forge_dir, return_metadata=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 1924, in render_azure
    return _render_ci_provider(
        "azure",
    ...<11 lines>...
        return_metadata=return_metadata,
    )
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 1226, in _render_ci_provider
    dump_subspace_config_files(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        metas, forge_dir, platform, arch, upload, forge_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 777, in dump_subspace_config_files
    configs, top_level_loop_vars = _collapse_subpackage_variants(
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        metas,
        ^^^^^^
    ...<3 lines>...
        forge_config,
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 578, in _collapse_subpackage_variants
    all_variants = _merge_deployment_target(all_variants, has_macdt)
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda_smithy/configure_feedstock.py", line 468, in _merge_deployment_target
    stdlib_lt_macdt = VersionOrder(v_stdlib) < VersionOrder(macdt)
                      ~~~~~~~~~~~~^^^^^^^^^^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda/models/version.py", line 49, in __call__
    return super().__call__(arg)
           ~~~~~~~~~~~~~~~~^^^^^
  File "/home/vpadulan/Programs/mambaforge/envs/conda-smithy/lib/python3.13/site-packages/conda/models/version.py", line 161, in __init__
    version = vstr.strip().rstrip().lower()
              ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'strip'
```

Note that the path to the custom `rattler-build-conda-compat` installation is because I just `pip install`ed the latest version 1.41 locally, as I couldn't find it via `conda install rattler-build-conda-compat`.

The way I fixed this issue is via the following patch
```
$: diff patched_configure_feedstock.py original_configure_feedstock.py

458,463d457
<             if isinstance(v_stdlib, list):
<                 assert len(v_stdlib) == 1
<                 v_stdlib = v_stdlib[0]
<             if isinstance(sdk, list):
<                 assert len(sdk) == 1
<                 sdk = sdk[0]
```

It looks like the `v_stdlib` and `sdk` variables in `configure_feedstock.py` are sometimes `str` and sometimes `list` with only one element containing the version string. With that patch, `conda-smithy rerender` works for `root-feedstock`.

Let me know if this is the right place to discuss this issue, if I should open a new issue on the same repository, or if I should open an issue to `conda-smithy`. And apologies for the noise!

**Comment by minrk** [comment]
@vepadulano I believe that was fixed by #79
